### ISSUE TITLE
RSVP count

### ISSUE THREAD

**Issue by cabbey** [SilphRoad/reports#3]
## I'm submitting a ...
  - [ ] bug report
  - [x] feature request

## **What is the expected behavior or new feature?**

It would be nice if when I send up a beacon I can specify additional folks will be with me.

## **What is the motivation / use case for changing the behavior?**

For example my current beacon says one person, but in reality there will be two of us, as my wife will be coming along. She has no interest in a Reddit account, or in traveling the road herself... how I find nests (and now raids) for our family doesn't seem to matter to her, just that I do. 

For small raids it doesn't matter, but for bigger ones, like 4 "stars", andcespecially in rural areas where folks might have to come from far away, the extra couple players not counted matter.

## **Other information**

I assume responding to someone else's beacon will need this too.

**Comment by Jamelephant** [comment]
Seconded :-)

**Comment by NibblesMcGiblet** [comment]
Came here to make this request myself. 
I'm a member of two fb groups - it's going to take awhile to get people in the groups to start using this system, and in the meantime I would like to be able to see the show of hands in our messenger chat and send up a beacon with a RSVP count already attached based on that show of hands. 

Example - yesterday we knew at least 5 people were meeting up at a raid before we even left the house. I would've loved to be able to send up a beacon saying I'm coming AND add a "+4" to it right away to indicate that non-TSR group members had also committed. 

Likewise, I would like to be able to respond to beacons with a +2 instead of always counting my "I'll be there!" as one person automatically, because my son also plays and is usually with me.

ADDITIONAL/EXPANSION ON THIS REQUEST: 
Then when others in the group decided to come as well, I would love it if the person who sent up the beacon could edit that RSVP number to show that fact. This way if a fb group admin wants to take the responsibility for the beacon system, he/she can do that and just monitor the fb chat group and add RSVPs for people who don't want to be bothered. Or, sometimes I'm stuck at home on the computer reading my group's chat and but can't go out and play with them - in that instance i could be the designated beacon-dropper for awhile and monitor the chat for RSVPs and adjust the count accordingly.

**Comment by fortepc** [comment]
This should probably be marked as done ;)
